### ISSUE TITLE
Fails to parse LF / whitespace at end of file

### ISSUE THREAD

**Issue by the-fermi-paradox** [allkern/koala#5]
Steps to reproduce:
1. Open `pow.k`
2. Add some extra new lines, white space, or just save on a POSIX-compliant machine
3. Now try to run `./bin/koala` on `pow.k`. The following error occurs:

> Unknown token at line 41 col 2

This is a problem in the lexer, specifically line 349. After consuming all of the whitespace, it needs to check for EOL again before exiting with a fail state.

**Comment by allkern** [comment]
Merged fix
